### ISSUE TITLE
Get CI running on github actions

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/bento_search#41]
Oops, it's still set up to run on travis... but isn't actually running on travis. We have to get CI working again. 

Getting CI green on current codebase is a pre-req/blocker to exploring officially supporting Rails 6 #39

**Comment by dkinzer** [comment]
I can try to give this a go, but I'm not sure what kind of access I would need to allow me to set this up.

**Comment by jrochkind** [comment]
If you figure out you need access you don't have, I'll give it to you! 

The potentially complicated part here is how many rails/ruby versions we were CI'ing in travis. 

Here are my extensive notes on moving projects from travis to github actions, some of htis may no longer be up to date, I dunno. https://bibwild.wordpress.com/2020/11/12/deep-dive-moving-ruby-projects-from-travis-to-github-actions-for-ci/

**Comment by jrochkind** [comment]
done, thanks @dkinzer !
